const mongoose = require("mongoose");
require("dotenv").config();

const {Post} = require("./models/Post");
const Profile = require("./models/Profile");
const Job = require("./models/Jobs"); // Import the Job model

const MONGO_URI = process.env.MONGODB_URI;

if (!MONGO_URI) {
    console.error("❌ Missing MONGODB_URI in .env");
    process.exit(1);
}

mongoose
    .connect(MONGO_URI, { useNewUrlParser: true, useUnifiedTopology: true })
    .then(() => console.log("✅ MongoDB connected"))
    .catch((err) => {
        console.error("❌ MongoDB connection error:", err);
        process.exit(1);
    });

const fakeData = [
    {
        "name": "Alex Johnson",
        "email": "alex.johnson@gmail.com",
        "password": "$2b$10$ngEO5QUzKzKrbXfIwsK7FuCJ9bZha5j7rMJkEmRQ1VAbYXScM9LFS"
    },
    {
        "name": "Sarah Chen",
        "email": "sarah.chen@yahoo.com",
        "password": "$2b$10$ngEO5QUzKzKrbXfIwsK7FuCJ9bZha5j7rMJkEmRQ1VAbYXScM9LFS"
    },
    {
        "name": "Michael Rodriguez",
        "email": "michael.rodriguez@hotmail.com",
        "password": "$2b$10$ngEO5QUzKzKrbXfIwsK7FuCJ9bZha5j7rMJkEmRQ1VAbYXScM9LFS"
    },
    {
        "name": "Emily Davis",
        "email": "emily.davis@outlook.com",
        "password": "$2b$10$ngEO5QUzKzKrbXfIwsK7FuCJ9bZha5j7rMJkEmRQ1VAbYXScM9LFS"
    },
    {
        "name": "James Wilson",
        "email": "james.wilson@gmail.com",
        "password": "$2b$10$ngEO5QUzKzKrbXfIwsK7FuCJ9bZha5j7rMJkEmRQ1VAbYXScM9LFS"
    },
    {
        "name": "Linda Thompson",
        "email": "linda.thompson@gmail.com",
        "password": "$2b$10$ngEO5QUzKzKrbXfIwsK7FuCJ9bZha5j7rMJkEmRQ1VAbYXScM9LFS"
    },
    {
        "name": "David Martinez",
        "email": "david.martinez@yahoo.com",
        "password": "$2b$10$ngEO5QUzKzKrbXfIwsK7FuCJ9bZha5j7rMJkEmRQ1VAbYXScM9LFS"
    },
    {
        "name": "Jennifer Lee",
        "email": "jennifer.lee@outlook.com",
        "password": "$2b$10$ngEO5QUzKzKrbXfIwsK7FuCJ9bZha5j7rMJkEmRQ1VAbYXScM9LFS"
    },
    {
        "name": "Robert Brown",
        "email": "robert.brown@hotmail.com",
        "password": "$2b$10$ngEO5QUzKzKrbXfIwsK7FuCJ9bZha5j7rMJkEmRQ1VAbYXScM9LFS"
    },
    {
        "name": "Karen Garcia",
        "email": "karen.garcia@gmail.com",
        "password": "$2b$10$ngEO5QUzKzKrbXfIwsK7FuCJ9bZha5j7rMJkEmRQ1VAbYXScM9LFS"
    },
    {
        "name": "Thomas Anderson",
        "email": "thomas.anderson@yahoo.com",
        "password": "$2b$10$ngEO5QUzKzKrbXfIwsK7FuCJ9bZha5j7rMJkEmRQ1VAbYXScM9LFS"
    },
    {
        "name": "Jessica Moore",
        "email": "jessica.moore@outlook.com",
        "password": "$2b$10$ngEO5QUzKzKrbXfIwsK7FuCJ9bZha5j7rMJkEmRQ1VAbYXScM9LFS"
    },
    {
        "name": "William White",
        "email": "william.white@hotmail.com",
        "password": "$2b$10$ngEO5QUzKzKrbXfIwsK7FuCJ9bZha5j7rMJkEmRQ1VAbYXScM9LFS"
    },
    {
        "name": "Patricia Harris",
        "email": "patricia.harris@gmail.com",
        "password": "$2b$10$ngEO5QUzKzKrbXfIwsK7FuCJ9bZha5j7rMJkEmRQ1VAbYXScM9LFS"
    },
    {
        "name": "Christopher Clark",
        "email": "christopher.clark@yahoo.com",
        "password": "$2b$10$ngEO5QUzKzKrbXfIwsK7FuCJ9bZha5j7rMJkEmRQ1VAbYXScM9LFS"
    },
    {
        "name": "Barbara Lewis",
        "email": "barbara.lewis@outlook.com",
        "password": "$2b$10$ngEO5QUzKzKrbXfIwsK7FuCJ9bZha5j7rMJkEmRQ1VAbYXScM9LFS"
    },
    {
        "name": "Daniel Walker",
        "email": "daniel.walker@hotmail.com",
        "password": "$2b$10$ngEO5QUzKzKrbXfIwsK7FuCJ9bZha5j7rMJkEmRQ1VAbYXScM9LFS"
    },
    {
        "name": "Nancy Hall",
        "email": "nancy.hall@gmail.com",
        "password": "$2b$10$ngEO5QUzKzKrbXfIwsK7FuCJ9bZha5j7rMJkEmRQ1VAbYXScM9LFS"
    },
    {
        "name": "Matthew Allen",
        "email": "matthew.allen@yahoo.com",
        "password": "$2b$10$ngEO5QUzKzKrbXfIwsK7FuCJ9bZha5j7rMJkEmRQ1VAbYXScM9LFS"
    },
    {
        "name": "Lisa Young",
        "email": "lisa.young@outlook.com",
        "password": "$2b$10$ngEO5QUzKzKrbXfIwsK7FuCJ9bZha5j7rMJkEmRQ1VAbYXScM9LFS"
    }
];

const jobs = [
    {
        JobTitle: "Frontend Developer",
        JobDescription: "Exciting opportunity for a skilled Frontend Developer to join our growing team. You will be responsible for building responsive and user-friendly web interfaces.",
        JobType: "Full Time",
        JobLocation: "Remote",
        salary: 90000,
        skills: ["React", "JavaScript", "CSS", "HTML"],
        companyName: "WebSolutions Inc.",
        companyDescription: "A dynamic company specializing in cutting-edge web solutions.",
        responsibilities: ["Develop new user-facing features", "Build reusable code and libraries", "Ensure the technical feasibility of UI/UX designs"],
        qualifications: ["Bachelor's degree in Computer Science or related field", "3+ years of experience in frontend development", "Proficiency in React and modern JavaScript frameworks"],
        applicationDeadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000), // 30 days from now
        experienceLevel: "Mid-level",
        industry: "Software Development",
        contactEmail: "hr@websolutions.com",
    },
    {
        JobTitle: "Backend Engineer",
        JobDescription: "We are seeking a talented Backend Engineer to design, develop, and maintain robust server-side applications and APIs.",
        JobType: "Full Time",
        JobLocation: "Onsite",
        salary: 110000,
        skills: ["Node.js", "Express", "MongoDB", "REST APIs"],
        companyName: "DataFlow Systems",
        companyDescription: "Innovating in data management and backend services.",
        responsibilities: ["Design and implement scalable APIs", "Manage database interactions", "Ensure high performance and responsiveness"],
        qualifications: ["Master's degree in Computer Science", "5+ years of experience in backend development", "Strong knowledge of Node.js and database systems"],
        applicationDeadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
        experienceLevel: "Senior-level",
        industry: "Information Technology",
        contactEmail: "careers@dataflow.com",
    },
    {
        JobTitle: "UI/UX Designer",
        JobDescription: "Join our creative team as a UI/UX Designer to craft intuitive and aesthetically pleasing user experiences for our digital products.",
        JobType: "Full Time",
        JobLocation: "Hybrid",
        salary: 75000,
        skills: ["Figma", "Sketch", "Adobe XD", "User Research"],
        companyName: "CreativeMinds Studio",
        companyDescription: "A design agency focused on user-centric product design.",
        responsibilities: ["Conduct user research and usability testing", "Create wireframes, prototypes, and high-fidelity mockups", "Collaborate with product and engineering teams"],
        qualifications: ["Bachelor's degree in Design or HCI", "2+ years of experience in UI/UX design", "Portfolio demonstrating strong design skills"],
        applicationDeadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
        experienceLevel: "Entry-level",
        industry: "Design",
        contactEmail: "design@creativeminds.com",
    },
    {
        JobTitle: "DevOps Engineer",
        JobDescription: "We are looking for a proactive DevOps Engineer to build and maintain our CI/CD pipelines and cloud infrastructure.",
        JobType: "Full Time",
        JobLocation: "Remote",
        salary: 105000,
        skills: ["AWS", "Docker", "Kubernetes", "CI/CD"],
        companyName: "CloudNative Solutions",
        companyDescription: "Pioneering cloud-native development and deployment.",
        responsibilities: ["Automate deployment processes", "Manage cloud resources", "Implement monitoring and logging solutions"],
        qualifications: ["Bachelor's degree in Computer Science", "4+ years of experience in DevOps", "Experience with AWS and containerization technologies"],
        applicationDeadline: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000),
        experienceLevel: "Mid-level",
        industry: "Cloud Computing",
        contactEmail: "devops@cloudnative.com",
    },
    {
        JobTitle: "Data Scientist",
        JobDescription: "Analyze complex datasets, build predictive models, and extract actionable insights to drive business decisions.",
        JobType: "Full Time",
        JobLocation: "Onsite",
        salary: 120000,
        skills: ["Python", "R", "Machine Learning", "SQL"],
        companyName: "Insightful Analytics",
        companyDescription: "Transforming data into strategic advantages for businesses.",
        responsibilities: ["Develop and implement machine learning models", "Perform statistical analysis", "Communicate findings to stakeholders"],
        qualifications: ["PhD or Master's in Data Science/Statistics", "3+ years of experience in data science", "Strong programming skills in Python or R"],
        applicationDeadline: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000),
        experienceLevel: "Senior-level",
        industry: "Data Analytics",
        contactEmail: "datajobs@insightful.com",
    },
    {
        JobTitle: "Mobile App Developer",
        JobDescription: "Design and build advanced applications for the iOS and Android platforms.",
        JobType: "Full Time",
        JobLocation: "Hybrid",
        salary: 95000,
        skills: ["Swift", "Kotlin", "React Native", "Firebase"],
        companyName: "AppGenius Labs",
        companyDescription: "Creating innovative mobile experiences for a global audience.",
        responsibilities: ["Collaborate with cross-functional teams to define, design, and ship new features", "Unit-test code for robustness, including edge cases, usability, and general reliability", "Work on bug fixing and improving application performance"],
        qualifications: ["Bachelor's degree in Computer Science", "3+ years of mobile development experience", "Published at least one original Android or iOS app"],
        applicationDeadline: new Date(Date.now() + 22 * 24 * 60 * 60 * 1000),
        experienceLevel: "Mid-level",
        industry: "Mobile Development",
        contactEmail: "mobilecareers@appgenius.com",
    },
    {
        JobTitle: "Product Manager",
        JobDescription: "Define product vision, strategy, and roadmap, and lead cross-functional teams to deliver impactful products.",
        JobType: "Full Time",
        JobLocation: "Onsite",
        salary: 130000,
        skills: ["Product Strategy", "Roadmapping", "Agile", "Market Research"],
        companyName: "NextGen Products",
        companyDescription: "Building the future of technology, one product at a time.",
        responsibilities: ["Gather and prioritize product and customer requirements", "Define the product roadmap", "Work closely with engineering, sales, marketing, and support"],
        qualifications: ["MBA or equivalent experience", "5+ years of product management experience", "Proven ability to manage all aspects of a successful product lifecycle"],
        applicationDeadline: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000),
        experienceLevel: "Director",
        industry: "Product Management",
        contactEmail: "pmjobs@nextgen.com",
    },
    {
        JobTitle: "Marketing Specialist",
        JobDescription: "Develop and execute marketing campaigns to increase brand awareness and drive customer acquisition.",
        JobType: "Full Time",
        JobLocation: "Remote",
        salary: 65000,
        skills: ["Digital Marketing", "SEO", "Content Marketing", "Social Media"],
        companyName: "BrandBoost Agency",
        companyDescription: "Helping businesses grow their brand and reach their audience.",
        responsibilities: ["Plan and execute all digital marketing, including SEO/SEM, marketing database, email, social media and display advertising campaigns", "Measure performance of all digital marketing campaigns", "Identify trends and insights, and optimize spend and performance based on the insights"],
        qualifications: ["Bachelor's degree in Marketing or related field", "2+ years of marketing experience", "Strong analytical skills and data-driven thinking"],
        applicationDeadline: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
        experienceLevel: "Entry-level",
        industry: "Marketing",
        contactEmail: "marketing@brandboost.com",
    },
    {
        JobTitle: "Technical Writer",
        JobDescription: "Create clear, concise, and comprehensive technical documentation for our software products.",
        JobType: "Full Time",
        JobLocation: "Remote",
        salary: 70000,
        skills: ["Documentation", "API Documentation", "Markdown", "Git"],
        companyName: "DocuWrite Solutions",
        companyDescription: "Making complex technology easy to understand.",
        responsibilities: ["Write and edit technical documentation", "Collaborate with engineers and product managers", "Maintain documentation standards"],
        qualifications: ["Bachelor's degree in Technical Communication or related field", "1+ year of technical writing experience", "Ability to translate complex technical concepts into clear, concise, and user-friendly documentation"],
        applicationDeadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
        experienceLevel: "Entry-level",
        industry: "Technical Communication",
        contactEmail: "docs@docuwrite.com",
    },
    {
        JobTitle: "HR Manager",
        JobDescription: "Lead our human resources department, focusing on talent acquisition, employee relations, and HR policies.",
        JobType: "Full Time",
        JobLocation: "Onsite",
        salary: 95000,
        skills: ["Recruitment", "Employee Relations", "HR Policies", "Onboarding"],
        companyName: "PeopleFirst HR",
        companyDescription: "Dedicated to fostering a positive and productive work environment.",
        responsibilities: ["Develop and implement HR strategies and initiatives", "Manage the recruitment and selection process", "Oversee employee relations and performance management"],
        qualifications: ["Bachelor's degree in Human Resources or Business Administration", "5+ years of HR experience", "Strong knowledge of labor laws and HR best practices"],
        applicationDeadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        experienceLevel: "Mid-level",
        industry: "Human Resources",
        contactEmail: "hr@peoplefirst.com",
    },
    {
        JobTitle: "Financial Analyst",
        JobDescription: "Provide financial planning and analysis, including budgeting, forecasting, and variance analysis.",
        JobType: "Full Time",
        JobLocation: "Onsite",
        salary: 85000,
        skills: ["Financial Modeling", "Budgeting", "Forecasting", "Excel"],
        companyName: "CapitalGrowth Advisors",
        companyDescription: "Empowering businesses with strategic financial insights.",
        responsibilities: ["Conduct financial analysis and prepare reports", "Assist in budget preparation and financial forecasting", "Evaluate financial performance and identify trends"],
        qualifications: ["Bachelor's degree in Finance or Accounting", "2+ years of experience in financial analysis", "CFA or CPA a plus"],
        applicationDeadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
        experienceLevel: "Entry-level",
        industry: "Financial Services",
        contactEmail: "finance@capitalgrowth.com",
    },
    {
        JobTitle: "Customer Support Specialist",
        JobDescription: "Deliver exceptional customer service and support to our users, resolving inquiries and issues efficiently.",
        JobType: "Full Time",
        JobLocation: "Remote",
        salary: 50000,
        skills: ["Customer Service", "Communication", "Problem-solving", "CRM Software"],
        companyName: "UserCare Solutions",
        companyDescription: "Committed to providing outstanding support and satisfaction.",
        responsibilities: ["Respond to customer inquiries via email, chat, and phone", "Troubleshoot and resolve technical issues", "Document customer interactions and feedback"],
        qualifications: ["High school diploma or equivalent", "1+ year of customer service experience", "Excellent communication and interpersonal skills"],
        applicationDeadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000),
        experienceLevel: "Entry-level",
        industry: "Customer Service",
        contactEmail: "support@usercare.com",
    },
    {
        JobTitle: "Sales Executive",
        JobDescription: "Drive revenue growth by identifying new business opportunities and building strong client relationships.",
        JobType: "Full Time",
        JobLocation: "Hybrid",
        salary: 70000,
        skills: ["Sales", "Negotiation", "CRM", "Lead Generation"],
        companyName: "GrowthPro Sales",
        companyDescription: "Accelerating business growth through strategic sales initiatives.",
        responsibilities: ["Identify and qualify new sales leads", "Conduct product presentations and demonstrations", "Negotiate contracts and close deals"],
        qualifications: ["Bachelor's degree in Business or related field", "3+ years of sales experience", "Proven track record of achieving sales targets"],
        applicationDeadline: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000),
        experienceLevel: "Mid-level",
        industry: "Sales",
        contactEmail: "sales@growthpro.com",
    },
    {
        JobTitle: "Network Administrator",
        JobDescription: "Manage and maintain our company's network infrastructure, ensuring optimal performance and security.",
        JobType: "Full Time",
        JobLocation: "Onsite",
        salary: 90000,
        skills: ["Networking", "Cisco", "Firewalls", "Troubleshooting"],
        companyName: "SecureNet Systems",
        companyDescription: "Providing robust and secure network solutions.",
        responsibilities: ["Install and configure network hardware and software", "Monitor network performance and troubleshoot issues", "Implement and maintain network security measures"],
        qualifications: ["Bachelor's degree in IT or related field", "3+ years of network administration experience", "Cisco certification (CCNA, CCNP) preferred"],
        applicationDeadline: new Date(Date.now() + 32 * 24 * 60 * 60 * 1000),
        experienceLevel: "Mid-level",
        industry: "IT Services",
        contactEmail: "itjobs@securenet.com",
    },
    {
        JobTitle: "Graphic Designer",
        JobDescription: "Create compelling visual content for marketing materials, websites, and social media.",
        JobType: "Full Time",
        JobLocation: "Hybrid",
        salary: 60000,
        skills: ["Adobe Creative Suite", "Typography", "Branding", "Illustration"],
        companyName: "VisualImpact Design",
        companyDescription: "Bringing ideas to life through stunning visual design.",
        responsibilities: ["Design marketing collateral and digital assets", "Develop brand guidelines and visual identities", "Collaborate with marketing and content teams"],
        qualifications: ["Bachelor's degree in Graphic Design or related field", "2+ years of graphic design experience", "Strong portfolio demonstrating creative and technical skills"],
        applicationDeadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
        experienceLevel: "Entry-level",
        industry: "Creative Services",
        contactEmail: "design@visualimpact.com",
    },
    {
        JobTitle: "QA Engineer",
        JobDescription: "Ensure the quality and reliability of our software products through comprehensive testing and quality assurance processes.",
        JobType: "Full Time",
        JobLocation: "Onsite",
        salary: 80000,
        skills: ["Manual Testing", "Automated Testing", "Jira", "Test Cases"],
        companyName: "QualityAssure Inc.",
        companyDescription: "Committed to delivering flawless software experiences.",
        responsibilities: ["Develop and execute test plans and test cases", "Identify, document, and track software bugs", "Collaborate with development teams to ensure quality throughout the SDLC"],
        qualifications: ["Bachelor's degree in Computer Science or related field", "2+ years of QA experience", "Experience with automated testing tools is a plus"],
        applicationDeadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
        experienceLevel: "Mid-level",
        industry: "Software Quality Assurance",
        contactEmail: "qa@qualityassure.com",
    },
    {
        JobTitle: "Project Manager",
        JobDescription: "Lead and manage software development projects from conception to completion, ensuring on-time and on-budget delivery.",
        JobType: "Full Time",
        JobLocation: "Hybrid",
        salary: 115000,
        skills: ["Project Planning", "Agile Methodologies", "Stakeholder Management", "Risk Management"],
        companyName: "Synergy Projects",
        companyDescription: "Delivering complex projects with precision and efficiency.",
        responsibilities: ["Define project scope, goals, and deliverables", "Develop detailed project plans and schedules", "Monitor project progress and manage risks"],
        qualifications: ["Bachelor's degree in Business or Project Management", "5+ years of project management experience", "PMP certification preferred"],
        applicationDeadline: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000),
        experienceLevel: "Senior-level",
        industry: "Project Management",
        contactEmail: "projects@synergy.com",
    },
    {
        JobTitle: "Content Writer",
        JobDescription: "Create engaging and informative content for our blog, website, and marketing campaigns.",
        JobType: "Part Time",
        JobLocation: "Remote",
        salary: 45000,
        skills: ["Content Creation", "SEO Writing", "Blogging", "Copywriting"],
        companyName: "WordCraft Content",
        companyDescription: "Crafting compelling narratives that resonate with audiences.",
        responsibilities: ["Write blog posts, articles, and website copy", "Optimize content for SEO", "Collaborate with marketing and design teams"],
        qualifications: ["Bachelor's degree in English, Journalism, or Marketing", "1+ year of content writing experience", "Strong writing and editing skills"],
        applicationDeadline: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
        experienceLevel: "Entry-level",
        industry: "Content Marketing",
        contactEmail: "content@wordcraft.com",
    },
    {
        JobTitle: "Cloud Architect",
        JobDescription: "Design and implement scalable, secure, and cost-effective cloud solutions on AWS, Azure, or GCP.",
        JobType: "Full Time",
        JobLocation: "Remote",
        salary: 140000,
        skills: ["AWS", "Azure", "GCP", "Cloud Security", "Infrastructure as Code"],
        companyName: "Skyline Cloud Solutions",
        companyDescription: "Leading the way in cloud infrastructure and migration.",
        responsibilities: ["Architect cloud solutions based on business requirements", "Provide technical leadership and guidance", "Ensure compliance with security best practices"],
        qualifications: ["Bachelor's degree in Computer Science or related field", "7+ years of experience in cloud architecture", "Certifications in AWS, Azure, or GCP"],
        applicationDeadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
        experienceLevel: "Director",
        industry: "Cloud Computing",
        contactEmail: "cloudjobs@skyline.com",
    },
    {
        JobTitle: "Cybersecurity Analyst",
        JobDescription: "Protect our organization's information systems from cyber threats and ensure data integrity and confidentiality.",
        JobType: "Full Time",
        JobLocation: "Onsite",
        salary: 100000,
        skills: ["Network Security", "Incident Response", "Vulnerability Assessment", "SIEM"],
        companyName: "Fortress Cyber",
        companyDescription: "Your trusted partner in digital defense.",
        responsibilities: ["Monitor security systems and respond to incidents", "Conduct vulnerability assessments and penetration testing", "Develop and implement security policies and procedures"],
        qualifications: ["Bachelor's degree in Cybersecurity or IT", "3+ years of experience in cybersecurity", "Relevant certifications (e.g., CompTIA Security+, CEH)"],
        applicationDeadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        experienceLevel: "Mid-level",
        industry: "Cybersecurity",
        contactEmail: "security@fortress.com",
    },
    {
        JobTitle: "Database Administrator",
        JobDescription: "Manage and maintain our database systems, ensuring high availability, performance, and data integrity.",
        JobType: "Full Time",
        JobLocation: "Onsite",
        salary: 90000,
        skills: ["SQL", "Database Management", "Performance Tuning", "Backup & Recovery"],
        companyName: "DataGuard Solutions",
        companyDescription: "Securing and optimizing critical data assets.",
        responsibilities: ["Install, configure, and upgrade database servers", "Monitor database performance and troubleshoot issues", "Implement and maintain database security and backup procedures"],
        qualifications: ["Bachelor's degree in Computer Science or related field", "3+ years of experience as a DBA", "Proficiency in SQL and database administration tools"],
        applicationDeadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
        experienceLevel: "Mid-level",
        industry: "Database Management",
        contactEmail: "dba@dataguard.com",
    },
    {
        JobTitle: "Machine Learning Engineer",
        JobDescription: "Develop and deploy machine learning models into production, working closely with data scientists and software engineers.",
        JobType: "Full Time",
        JobLocation: "Remote",
        salary: 135000,
        skills: ["Python", "TensorFlow", "PyTorch", "Deployment", "MLOps"],
        companyName: "AI Innovations",
        companyDescription: "Pushing the boundaries of artificial intelligence.",
        responsibilities: ["Build and optimize ML pipelines", "Deploy models to production environments", "Monitor model performance and retrain as needed"],
        qualifications: ["Master's or PhD in Computer Science, AI, or related field", "3+ years of experience in ML engineering", "Strong programming skills and understanding of ML algorithms"],
        applicationDeadline: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000),
        experienceLevel: "Senior-level",
        industry: "Artificial Intelligence",
        contactEmail: "mljobs@aiinnovations.com",
    },
    {
        JobTitle: "UX Researcher",
        JobDescription: "Conduct user research to understand user behaviors, needs, and motivations, informing product design and development.",
        JobType: "Full Time",
        JobLocation: "Hybrid",
        salary: 85000,
        skills: ["User Interviews", "Usability Testing", "Survey Design", "Data Analysis"],
        companyName: "UserCentric Insights",
        companyDescription: "Unlocking deep user understanding to create impactful products.",
        responsibilities: ["Plan and conduct qualitative and quantitative user research", "Analyze research data and synthesize findings", "Present insights and recommendations to product teams"],
        qualifications: ["Bachelor's or Master's degree in HCI, Psychology, or related field", "2+ years of UX research experience", "Proficiency in various research methodologies"],
        applicationDeadline: new Date(Date.now() + 22 * 24 * 60 * 60 * 1000),
        experienceLevel: "Mid-level",
        industry: "User Experience",
        contactEmail: "uxr@usercentric.com",
    },
    {
        JobTitle: "Full Stack Developer",
        JobDescription: "Develop and maintain both frontend and backend components of our web applications.",
        JobType: "Full Time",
        JobLocation: "Onsite",
        salary: 100000,
        skills: ["React", "Node.js", "MongoDB", "AWS", "TypeScript"],
        companyName: "Unified Solutions",
        companyDescription: "Building seamless and robust full-stack applications.",
        responsibilities: ["Design and implement APIs and database schemas", "Develop responsive user interfaces", "Participate in code reviews and team discussions"],
        qualifications: ["Bachelor's degree in Computer Science or related field", "4+ years of full-stack development experience", "Strong understanding of web technologies"],
        applicationDeadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        experienceLevel: "Senior-level",
        industry: "Software Development",
        contactEmail: "fullstack@unified.com",
    },
    {
        JobTitle: "IT Support Specialist",
        JobDescription: "Provide technical assistance and support to our internal employees, resolving hardware and software issues.",
        JobType: "Full Time",
        JobLocation: "Onsite",
        salary: 55000,
        skills: ["Troubleshooting", "Windows", "macOS", "Hardware Support"],
        companyName: "TechHelp Services",
        companyDescription: "Your go-to for all IT needs.",
        responsibilities: ["Respond to IT support tickets", "Diagnose and resolve technical problems", "Provide user training and guidance"],
        qualifications: ["Associate's degree in IT or equivalent experience", "1+ year of IT support experience", "Strong communication and customer service skills"],
        applicationDeadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000),
        experienceLevel: "Entry-level",
        industry: "IT Services",
        contactEmail: "itsupport@techhelp.com",
    },
    {
        JobTitle: "Business Analyst",
        JobDescription: "Bridge the gap between business needs and technical solutions, translating requirements into actionable plans.",
        JobType: "Full Time",
        JobLocation: "Hybrid",
        salary: 80000,
        skills: ["Requirements Gathering", "Process Mapping", "SQL", "Data Analysis"],
        companyName: "Stratagem Consulting",
        companyDescription: "Empowering businesses with strategic insights and solutions.",
        responsibilities: ["Gather and analyze business requirements", "Create functional and technical specifications", "Facilitate communication between stakeholders and development teams"],
        qualifications: ["Bachelor's degree in Business, IT, or related field", "3+ years of experience as a Business Analyst", "Strong analytical and problem-solving skills"],
        applicationDeadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
        experienceLevel: "Mid-level",
        industry: "Consulting",
        contactEmail: "ba@stratagem.com",
    },
    {
        JobTitle: "Software Development Intern",
        JobDescription: "Gain hands-on experience in software development, working on real-world projects under the guidance of senior engineers.",
        JobType: "Internship",
        JobLocation: "Onsite",
        salary: 30000,
        skills: ["JavaScript", "Python", "Data Structures", "Algorithms"],
        companyName: "FutureTech Innovations",
        companyDescription: "Nurturing the next generation of tech talent.",
        responsibilities: ["Assist in coding and debugging applications", "Participate in code reviews", "Learn and apply new technologies"],
        qualifications: ["Currently pursuing a Bachelor's degree in Computer Science or related field", "Basic understanding of programming concepts", "Eagerness to learn and a strong work ethic"],
        applicationDeadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
        experienceLevel: "Entry-level",
        industry: "Software Development",
        contactEmail: "internships@futuretech.com",
    },
    {
        JobTitle: "Senior Software Engineer",
        JobDescription: "Lead the design and development of complex software systems, mentoring junior engineers and driving technical excellence.",
        JobType: "Full Time",
        JobLocation: "Onsite",
        salary: 150000,
        skills: ["System Design", "Microservices", "Cloud Architecture", "Leadership"],
        companyName: "EliteDev Solutions",
        companyDescription: "Building high-performance, scalable software for enterprise clients.",
        responsibilities: ["Lead technical design and implementation", "Mentor and guide engineering team members", "Contribute to architectural decisions"],
        qualifications: ["Master's degree in Computer Science", "7+ years of software development experience", "Proven track record of leading successful projects"],
        applicationDeadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
        experienceLevel: "Senior-level",
        industry: "Software Development",
        contactEmail: "seniorjobs@elitedev.com",
    },
    {
        JobTitle: "Product Designer",
        JobDescription: "Shape the user experience of our products from concept to launch, focusing on user-centered design principles.",
        JobType: "Full Time",
        JobLocation: "Hybrid",
        salary: 95000,
        skills: ["UX Design", "UI Design", "Prototyping", "Design Systems"],
        companyName: "InnovateDesign Co.",
        companyDescription: "Crafting intuitive and delightful digital experiences.",
        responsibilities: ["Conduct user research and translate insights into design solutions", "Create wireframes, user flows, and prototypes", "Collaborate with product managers and engineers"],
        qualifications: ["Bachelor's degree in Design, HCI, or related field", "3+ years of product design experience", "Strong portfolio showcasing UX/UI design skills"],
        applicationDeadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        experienceLevel: "Mid-level",
        industry: "Product Design",
        contactEmail: "design@innovatedesign.com",
    },
    {
        JobTitle: "Data Engineer",
        JobDescription: "Build and maintain scalable data pipelines and infrastructure to support our data science and analytics initiatives.",
        JobType: "Full Time",
        JobLocation: "Remote",
        salary: 120000,
        skills: ["Python", "SQL", "ETL", "Cloud Data Platforms", "Spark"],
        companyName: "DataForge Analytics",
        companyDescription: "Forging robust data foundations for intelligent insights.",
        responsibilities: ["Design, build, and maintain data pipelines", "Optimize data storage and retrieval systems", "Ensure data quality and integrity"],
        qualifications: ["Bachelor's degree in Computer Science or related field", "4+ years of experience in data engineering", "Proficiency in Python and SQL"],
        applicationDeadline: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000),
        experienceLevel: "Senior-level",
        industry: "Data Engineering",
        contactEmail: "dataeng@dataforge.com",
    },
    {
        JobTitle: "Marketing Analyst",
        JobDescription: "Analyze marketing campaign performance, identify trends, and provide data-driven recommendations for optimization.",
        JobType: "Full Time",
        JobLocation: "Onsite",
        salary: 70000,
        skills: ["Google Analytics", "Data Visualization", "Excel", "SQL"],
        companyName: "MetricGrowth Marketing",
        companyDescription: "Driving marketing success through actionable data insights.",
        responsibilities: ["Track and report on marketing campaign performance", "Develop dashboards and reports", "Provide insights and recommendations for marketing optimization"],
        qualifications: ["Bachelor's degree in Marketing, Business, or Statistics", "2+ years of experience in marketing analytics", "Strong analytical and quantitative skills"],
        applicationDeadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
        experienceLevel: "Entry-level",
        industry: "Marketing Analytics",
        contactEmail: "analyst@metricgrowth.com",
    },
    {
        JobTitle: "Technical Support Engineer",
        JobDescription: "Provide advanced technical support to enterprise clients, troubleshooting complex software and system issues.",
        JobType: "Full Time",
        JobLocation: "Remote",
        salary: 75000,
        skills: ["Linux", "Networking", "Troubleshooting", "Customer Service"],
        companyName: "ProSupport Tech",
        companyDescription: "Expert technical assistance for complex IT environments.",
        responsibilities: ["Resolve complex technical issues for clients", "Provide in-depth product support and guidance", "Document solutions and create knowledge base articles"],
        qualifications: ["Bachelor's degree in IT or related field", "3+ years of technical support experience", "Strong problem-solving and communication skills"],
        applicationDeadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
        experienceLevel: "Mid-level",
        industry: "Technical Support",
        contactEmail: "techsupport@prosupport.com",
    },
    {
        JobTitle: "HR Coordinator",
        JobDescription: "Assist the HR team with various administrative tasks, including recruitment support, onboarding, and record keeping.",
        JobType: "Part Time",
        JobLocation: "Onsite",
        salary: 40000,
        skills: ["HR Administration", "Recruitment Support", "Data Entry", "Communication"],
        companyName: "TalentLink HR",
        companyDescription: "Connecting talent with opportunity.",
        responsibilities: ["Support the recruitment process (scheduling interviews, posting jobs)", "Assist with new employee onboarding", "Maintain HR records and databases"],
        qualifications: ["Associate's degree or equivalent experience", "1+ year of administrative or HR experience", "Excellent organizational and communication skills"],
        applicationDeadline: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
        experienceLevel: "Entry-level",
        industry: "Human Resources",
        contactEmail: "hr@talentlink.com",
    },
];

const seedDatabase = async () => {
    try {
        await Job.deleteMany({});
        await Job.insertMany(jobs);
        console.log("✅ Jobs data seeded successfully!");
    } catch (error) {
        console.error("❌ Error seeding jobs data:", error);
    } finally {
        mongoose.disconnect();
    }
};

seedDatabase();
